// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM56KyU0iY1LVbZ9HNOOji2SgjRREUOMI',
    appId: '1:891226107480:web:d37be98ff4c5f74e50a42d',
    messagingSenderId: '891226107480',
    projectId: 'alert-master-cd304',
    authDomain: 'alert-master-cd304.firebaseapp.com',
    storageBucket: 'alert-master-cd304.firebasestorage.app',
    measurementId: 'G-EGPYMCC0Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMVzq-uL2YZ08DTreXq2610GkM2adzcA',
    appId: '1:891226107480:android:1de2f7e57924bffd50a42d',
    messagingSenderId: '891226107480',
    projectId: 'alert-master-cd304',
    storageBucket: 'alert-master-cd304.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArz9Pw950JGCuuZJcpvPAzvZhRYTJXzIE',
    appId: '1:891226107480:ios:d30630a0548ecbfd50a42d',
    messagingSenderId: '891226107480',
    projectId: 'alert-master-cd304',
    storageBucket: 'alert-master-cd304.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArz9Pw950JGCuuZJcpvPAzvZhRYTJXzIE',
    appId: '1:891226107480:ios:d30630a0548ecbfd50a42d',
    messagingSenderId: '891226107480',
    projectId: 'alert-master-cd304',
    storageBucket: 'alert-master-cd304.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM56KyU0iY1LVbZ9HNOOji2SgjRREUOMI',
    appId: '1:891226107480:web:1a23e1ad9f28561750a42d',
    messagingSenderId: '891226107480',
    projectId: 'alert-master-cd304',
    authDomain: 'alert-master-cd304.firebaseapp.com',
    storageBucket: 'alert-master-cd304.firebasestorage.app',
    measurementId: 'G-KH08ZJRPEQ',
  );
}
